//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgurSniper.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImgurSniper.UI.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Snapping....
        /// </summary>
        public static string afterSnapping {
            get {
                return ResourceManager.GetString("afterSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On all Monitors.
        /// </summary>
        public static string allMonitor {
            get {
                return ResourceManager.GetString("allMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Settings were applied!.
        /// </summary>
        public static string applied {
            get {
                return ResourceManager.GetString("applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically search for Updates.
        /// </summary>
        public static string autoUpdate {
            get {
                return ResourceManager.GetString("autoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically upload to Imgur.
        /// </summary>
        public static string autoUploadImgur {
            get {
                return ResourceManager.GetString("autoUploadImgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for Updates....
        /// </summary>
        public static string checkingUpdate {
            get {
                return ResourceManager.GetString("checkingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Commits on GitHub.
        /// </summary>
        public static string commitsDisplay {
            get {
                return ResourceManager.GetString("commitsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Imgur....
        /// </summary>
        public static string contactImgur {
            get {
                return ResourceManager.GetString("contactImgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        public static string contextMenu {
            get {
                return ResourceManager.GetString("contextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click any File in Windows Explorer (or on your Desktop) to open the Context Menu. To quickly upload any File to Imgur, you can now click &quot;Upload to Imgur&quot;.
        /// </summary>
        public static string contextMenuDesc {
            get {
                return ResourceManager.GetString("contextMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image to Clipboard.
        /// </summary>
        public static string copyClipboard {
            get {
                return ResourceManager.GetString("copyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply changes!.
        /// </summary>
        public static string couldNotApply {
            get {
                return ResourceManager.GetString("couldNotApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download ZIP Archive from github.com!.
        /// </summary>
        public static string couldNotDownload {
            get {
                return ResourceManager.GetString("couldNotDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load Config!.
        /// </summary>
        public static string couldNotLoad {
            get {
                return ResourceManager.GetString("couldNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Shift + .
        /// </summary>
        public static string ctrlShift {
            get {
                return ResourceManager.GetString("ctrlShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On current Monitor.
        /// </summary>
        public static string curMonitor {
            get {
                return ResourceManager.GetString("curMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable the ImgurSniper Tray Service?.
        /// </summary>
        public static string disablingTrayWarning {
            get {
                return ResourceManager.GetString("disablingTrayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading from github.com/mrousavy/ImgurSniper....
        /// </summary>
        public static string downloadingGitHub {
            get {
                return ResourceManager.GetString("downloadingGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Update...
        /// </summary>
        public static string downloadingUpdate {
            get {
                return ResourceManager.GetString("downloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Magnifying Glass.
        /// </summary>
        public static string enMagnifying {
            get {
                return ResourceManager.GetString("enMagnifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading Config!
        ///(&quot;{0}&quot;).
        /// </summary>
        public static string errorConfig {
            get {
                return ResourceManager.GetString("errorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve Version/Update info from GitHub!.
        /// </summary>
        public static string failedUpdate {
            get {
                return ResourceManager.GetString("failedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF.
        /// </summary>
        public static string gif {
            get {
                return ResourceManager.GetString("gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS:.
        /// </summary>
        public static string gifFps {
            get {
                return ResourceManager.GetString("gifFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FPS.
        /// </summary>
        public static string gifFpsVal {
            get {
                return ResourceManager.GetString("gifFpsVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Length:.
        /// </summary>
        public static string gifLength {
            get {
                return ResourceManager.GetString("gifLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Seconds.
        /// </summary>
        public static string gifLengthVal {
            get {
                return ResourceManager.GetString("gifLengthVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey (GIF):.
        /// </summary>
        public static string hotkeyGif {
            get {
                return ResourceManager.GetString("hotkeyGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey (Image):.
        /// </summary>
        public static string hotkeyImg {
            get {
                return ResourceManager.GetString("hotkeyImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Format:.
        /// </summary>
        public static string imgFormat {
            get {
                return ResourceManager.GetString("imgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgur Account.
        /// </summary>
        public static string imgurAcc {
            get {
                return ResourceManager.GetString("imgurAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgur Account (signed in as &quot;{0}&quot;).
        /// </summary>
        public static string imgurAccSignedIn {
            get {
                return ResourceManager.GetString("imgurAccSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, ImgurSniper could not be found on your System!.
        /// </summary>
        public static string imgurSniperNotFound {
            get {
                return ResourceManager.GetString("imgurSniperNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string initializing {
            get {
                return ResourceManager.GetString("initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language successfully changed, to proceed,
        ///you have to restart ImgurSniper.
        ///Do you want to restart ImgurSniper now?.
        /// </summary>
        public static string langChanged {
            get {
                return ResourceManager.GetString("langChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Configuration....
        /// </summary>
        public static string loadConf {
            get {
                return ResourceManager.GetString("loadConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged in! Hi, {0}!.
        /// </summary>
        public static string loggedIn {
            get {
                return ResourceManager.GetString("loggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe a Window on all connected Monitors (May be slower).
        /// </summary>
        public static string notOnlyMouse {
            get {
                return ResourceManager.GetString("notOnlyMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Snipe a Window on the Monitor the Mouse Cursor is currently on..
        /// </summary>
        public static string onlyMouse {
            get {
                return ResourceManager.GetString("onlyMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image in Browser after Upload.
        /// </summary>
        public static string openBrowser {
            get {
                return ResourceManager.GetString("openBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other....
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string pageClipboard {
            get {
                return ResourceManager.GetString("pageClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As soon as you have finished cropping the desired Rectangle, ImgurSniper will automatically copy the URL to Imgur or the whole Image itself (depending on your Settings) to your Clipboard, so you&apos;re ready to send it immediately!.
        /// </summary>
        public static string pageClipboardDesc {
            get {
                return ResourceManager.GetString("pageClipboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string pageDraw {
            get {
                return ResourceManager.GetString("pageDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Snipe Mode, you can draw on your screen to show the receiver something important (Circle, Arrows, ...), hide some Information, or show your drawing Skills!
        ///To enter the drawing Mode, you just need to press Space once in Snap Mode!.
        /// </summary>
        public static string pageDrawDesc {
            get {
                return ResourceManager.GetString("pageDrawDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string pageGeneral {
            get {
                return ResourceManager.GetString("pageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImgurSniper is an easy to use, fast and simple tool to help you share Images better.
        ///Open ImgurSniper with your Hotkey (default: Ctrl + Shift + X) and Crop an Image, or right click an Image File and click &quot;Upload to Imgur&quot; to upload the Image.
        ///See &quot;Snipe&quot; and &quot;Tray&quot; for more Information about the Program.
        ///
        ///Licensed under MIT Open Source License on github.com/mrousavy/ImgurSniper, you can modify the Program for your needs. To contribute, click the Fork button (top right) on GitHub, customize your Project [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pageGeneralDesc {
            get {
                return ResourceManager.GetString("pageGeneralDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF.
        /// </summary>
        public static string pageGif {
            get {
                return ResourceManager.GetString("pageGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To snipe a new GIF you have to press your GIF Hotkey (Default: Ctrl + Shift + G) or right-click the ImgurSniper Tray Icon (right side of your Taskbar) and hit &quot;GIF&quot;. Instead of sharing a single Image, you now can share a short Screen Recording!
        ///
        ///As soon as you selected your desired area, ImgurSniper will start recording the GIF. The blue Progress Bar below the grey Area will show you the Progress of the GIF (Once the Progress Bar is full, the screen recording will automatically stop and begin uploading th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pageGifDesc {
            get {
                return ResourceManager.GetString("pageGifDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string pagePrivacy {
            get {
                return ResourceManager.GetString("pagePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImgurSniper does not collect any data, the only Information being uploaded is your Image. (The Image itself is private, and only accessible for users with the link.)
        ///As the ImgurSniper C# Project is on GitHub, you can easily view 100% of the Code.
        ///ImgurSniper uses OAuth2.0 for Authentication, so no Password or username will be stored, and you can revoke access anytime..
        /// </summary>
        public static string pagePrivacyDesc {
            get {
                return ResourceManager.GetString("pagePrivacyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click.
        /// </summary>
        public static string pageRightClick {
            get {
                return ResourceManager.GetString("pageRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you Right Click with your Mouse in Snipe Mode, ImgurSniper will detect the Window you clicked, and upload the cropped Image of that Window to Imgur. ImgurSniper does detect a whole Window when you click the Titlebar and even Client Area(s) (Areas inside a Window)..
        /// </summary>
        public static string pageRightClickDesc {
            get {
                return ResourceManager.GetString("pageRightClickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe.
        /// </summary>
        public static string pageSnipe {
            get {
                return ResourceManager.GetString("pageSnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press your Hotkey (default: Ctrl + Shift + X) to open ImgurSniper in Snipe mode. In Snipe Mode, you can hold down your mouse and draw a Rectangle to select the Area you want to upload.
        ///Once you release the mouse, the Image will automatically be uploaded to Imgur (if enabled), saved as a file (optionally), and the Link (or Image itself) will be copied to your Clipboard. Depending on your Settings, the Image will be automatically opened for you to see aswell.
        ///Pro Tip: Hit Ctrl + A to instantly create a Scre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pageSnipeDesc {
            get {
                return ResourceManager.GetString("pageSnipeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray.
        /// </summary>
        public static string pageTray {
            get {
                return ResourceManager.GetString("pageTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tray Service is running in the Background, so you can activate ImgurSniper with your Hotkey (default: Ctrl + Shift + X) way faster than launching the executable. The Tray Service is optimized to use as little processing power as possible, so your PC is definetly not slowed down. You can find the ImgurSniper Tray Program in the bottom right corner of your Screen, Right Click the Icon to open the Menu..
        /// </summary>
        public static string pageTrayDesc {
            get {
                return ResourceManager.GetString("pageTrayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Path does not exist!.
        /// </summary>
        public static string pathNotExist {
            get {
                return ResourceManager.GetString("pathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the PIN you received on the Website..
        /// </summary>
        public static string plsPin {
            get {
                return ResourceManager.GetString("plsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any Key...
        ///(ESC to cancel).
        /// </summary>
        public static string pressKey {
            get {
                return ResourceManager.GetString("pressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string quality {
            get {
                return ResourceManager.GetString("quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string repair {
            get {
                return ResourceManager.GetString("repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repaired ImgurSniper. Please restart ImgurSniper to complete!.
        /// </summary>
        public static string repairedImgurSniper {
            get {
                return ResourceManager.GetString("repairedImgurSniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save snapped Images locally.
        /// </summary>
        public static string saveLocally {
            get {
                return ResourceManager.GetString("saveLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Path where ImgurSniper should save Images..
        /// </summary>
        public static string selectPath {
            get {
                return ResourceManager.GetString("selectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string settingsCapture {
            get {
                return ResourceManager.GetString("settingsCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string settingsEvents {
            get {
                return ResourceManager.GetString("settingsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string settingsHome {
            get {
                return ResourceManager.GetString("settingsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgur.
        /// </summary>
        public static string settingsImgur {
            get {
                return ResourceManager.GetString("settingsImgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string settingsOther {
            get {
                return ResourceManager.GetString("settingsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mouse.
        /// </summary>
        public static string showMouse {
            get {
                return ResourceManager.GetString("showMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string singIn {
            get {
                return ResourceManager.GetString("singIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string singOut {
            get {
                return ResourceManager.GetString("singOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip these ImgurSniper Updates.
        /// </summary>
        public static string skipTooltip {
            get {
                return ResourceManager.GetString("skipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe!.
        /// </summary>
        public static string snipe {
            get {
                return ResourceManager.GetString("snipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgur Sniper Settings.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImgurSniper Tray/Background Service.
        /// </summary>
        public static string trayService {
            get {
                return ResourceManager.GetString("trayService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImgurSniper Tray Service is not running!.
        /// </summary>
        public static string trayServiceNotRunning {
            get {
                return ResourceManager.GetString("trayServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start ImgurSniper tray service!.
        /// </summary>
        public static string trayServiceStartFail {
            get {
                return ResourceManager.GetString("trayServiceStartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting.
        /// </summary>
        public static string troubleshooting {
            get {
                return ResourceManager.GetString("troubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! It looks like you encountered an Error while uploading an Image.
        ///If this problem occurs more often, try the following:
        ///    • Try logging in with your Imgur Account
        ///    • Change the Image Format from .PNG to .JPEG
        ///    • Restart your Computer
        ///    • Make sure that you have Write Permissions to Documents/ImgurSniper
        ///    • Make sure that your GIF is not too long, too big, or has too many FPS!
        ///Does the Error still occur? Maybe your Internet Connection
        ///is too slow for the Imgur Service..
        /// </summary>
        public static string troubleshootingTips {
            get {
                return ResourceManager.GetString("troubleshootingTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! Sorry about that, it seems like ImgurSniper ran into an unexpected Error!
        ///But no worries, you can help out and get this Problem fixed asap!
        ///Do you want to help out and submit a ticket?
        ///(If you click yes, a new Browser Window opens).
        /// </summary>
        public static string unhandledError {
            get {
                return ResourceManager.GetString("unhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured in ImgurSniper.
        ///Error Message: &quot;{0}&quot;
        ///
        ///Do you want to see more details about that Error?.
        /// </summary>
        public static string unhandledErrorDescription {
            get {
                return ResourceManager.GetString("unhandledErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured!\r\nShow this to the smart Computer apes: {0}.
        /// </summary>
        public static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ImgurSniper Update is available to download! (v{0}/{1}).
        /// </summary>
        public static string updateAvailable {
            get {
                return ResourceManager.GetString("updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last: {0}.
        /// </summary>
        public static string updateLast {
            get {
                return ResourceManager.GetString("updateLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Updates.
        /// </summary>
        public static string updateNow {
            get {
                return ResourceManager.GetString("updateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use .JPEG for Images (Faster uploads, lower Quality).
        /// </summary>
        public static string useJPEG {
            get {
                return ResourceManager.GetString("useJPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use .PNG for Images (Slower uploads, higher Quality).
        /// </summary>
        public static string usePNG {
            get {
                return ResourceManager.GetString("usePNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Print Key as Shortcut.
        /// </summary>
        public static string usePrint {
            get {
                return ResourceManager.GetString("usePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Info.
        /// </summary>
        public static string verInfo {
            get {
                return ResourceManager.GetString("verInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Images.
        /// </summary>
        public static string viewPics {
            get {
                return ResourceManager.GetString("viewPics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to apply the changes you made?.
        /// </summary>
        public static string wantToApply {
            get {
                return ResourceManager.GetString("wantToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to snipe.
        /// </summary>
        public static string whereSnipe {
            get {
                return ResourceManager.GetString("whereSnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong PIN? Could not login to Imgur! ({0}).
        /// </summary>
        public static string wrongPin {
            get {
                return ResourceManager.GetString("wrongPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
