//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleanup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cleanup.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad to see you go! Bye :(.
        /// </summary>
        internal static string byeMSG {
            get {
                return ResourceManager.GetString("byeMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Program Files....
        /// </summary>
        internal static string cleanProgramFiles {
            get {
                return ResourceManager.GetString("cleanProgramFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up User Data....
        /// </summary>
        internal static string cleanUserData {
            get {
                return ResourceManager.GetString("cleanUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for all ImgurSniper instances to exit....
        /// </summary>
        internal static string closeInstance {
            get {
                return ResourceManager.GetString("closeInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\nPress any key to continue.
        /// </summary>
        internal static string continueMSG {
            get {
                return ResourceManager.GetString("continueMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured!\nShow this to the smart Computer apes: {0}.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImgurSniper Uninstaller.
        /// </summary>
        internal static string uninstallTitle {
            get {
                return ResourceManager.GetString("uninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Files were not successfully removed!.
        /// </summary>
        internal static string wrongUninstall {
            get {
                return ResourceManager.GetString("wrongUninstall", resourceCulture);
            }
        }
    }
}
