//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgurSniper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImgurSniper.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click or Press .
        /// </summary>
        internal static string clickorpress {
            get {
                return ResourceManager.GetString("clickorpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Shift + {0}.
        /// </summary>
        internal static string ctrlShiftShortcut {
            get {
                return ResourceManager.GetString("ctrlShiftShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured in ImgurSniper.UI!\nImgurSniper has to shut down!\nWould you like to see a detailed Exception Info? ({0}).
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading File(s), make sure to check your Internet connection and see if the File is a valid Image file!.
        /// </summary>
        internal static string errorInstantUpload {
            get {
                return ResourceManager.GetString("errorInstantUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image was copied to your Clipboard!.
        /// </summary>
        internal static string imgclipboard {
            get {
                return ResourceManager.GetString("imgclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Image Width and/or Height is too small!.
        /// </summary>
        internal static string imgSize {
            get {
                return ResourceManager.GetString("imgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size exceeds 10MB, to increase this please Login to Imgur!.
        /// </summary>
        internal static string imgToBig {
            get {
                return ResourceManager.GetString("imgToBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to Imgur has been copied to your Clipboard!.
        /// </summary>
        internal static string linkclipboard {
            get {
                return ResourceManager.GetString("linkclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}\n\n.
        /// </summary>
        internal static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured! (Show this to the Smart Computer Apes: {0}).
        /// </summary>
        internal static string otherErrorMsg {
            get {
                return ResourceManager.GetString("otherErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Print Key.
        /// </summary>
        internal static string printKeyShortcut {
            get {
                return ResourceManager.GetString("printKeyShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to Snipe a new Image.
        /// </summary>
        internal static string toSnipeNew {
            get {
                return ResourceManager.GetString("toSnipeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured in ImgurSniper.UI!
        ///ImgurSniper has to shut down!
        ///Would you like to see a detailed Exception Info?
        ///.
        /// </summary>
        internal static string unhandledError {
            get {
                return ResourceManager.GetString("unhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Image... ({0} KB).
        /// </summary>
        internal static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading Image to Imgur! ({0}).
        /// </summary>
        internal static string uploadingError {
            get {
                return ResourceManager.GetString("uploadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Images... ({0} KB) ({1} of {2}).
        /// </summary>
        internal static string uploadingFiles {
            get {
                return ResourceManager.GetString("uploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload with ImgurSniper.
        /// </summary>
        internal static string uploadTitle {
            get {
                return ResourceManager.GetString("uploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops, something went wrong!.
        /// </summary>
        internal static string whoops {
            get {
                return ResourceManager.GetString("whoops", resourceCulture);
            }
        }
    }
}
