//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgurSniper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImgurSniper.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click or Press .
        /// </summary>
        public static string clickorpress {
            get {
                return ResourceManager.GetString("clickorpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg.exe failed to convert MP4 to GIF!.
        /// </summary>
        public static string couldNotCreateGif {
            get {
                return ResourceManager.GetString("couldNotCreateGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find FFmpegManager.exe!.
        /// </summary>
        public static string couldNotFindFfmpeg {
            get {
                return ResourceManager.GetString("couldNotFindFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not install ffmpeg.exe!.
        /// </summary>
        public static string couldNotInstallFfmpeg {
            get {
                return ResourceManager.GetString("couldNotInstallFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg.exe could not start screen recording!.
        /// </summary>
        public static string couldNotStartFfmpeg {
            get {
                return ResourceManager.GetString("couldNotStartFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not begin recording GIF!.
        /// </summary>
        public static string couldNotStartRecording {
            get {
                return ResourceManager.GetString("couldNotStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Shift + {0}.
        /// </summary>
        public static string ctrlShiftShortcut {
            get {
                return ResourceManager.GetString("ctrlShiftShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured in ImgurSniper!
        ///ImgurSniper has to shut down!
        ///Would you like to see a detailed Exception Info? ({0}).
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading File(s), make sure to check your Internet connection and see if the File is a valid Image file!.
        /// </summary>
        public static string errorInstantUpload {
            get {
                return ResourceManager.GetString("errorInstantUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured!.
        /// </summary>
        public static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg encountered an unexpected Error!
        ///Do you want to see the FFmpeg Log?.
        /// </summary>
        public static string ffmpegError {
            get {
                return ResourceManager.GetString("ffmpegError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF.
        /// </summary>
        public static string gif {
            get {
                return ResourceManager.GetString("gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF was copied to your Clipboard!.
        /// </summary>
        public static string gifCopyClipboard {
            get {
                return ResourceManager.GetString("gifCopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF was copied to your Clipboard and saved to file!.
        /// </summary>
        public static string gifCopyClipboardSaved {
            get {
                return ResourceManager.GetString("gifCopyClipboardSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image was copied to your Clipboard!.
        /// </summary>
        public static string imgCopyClipboard {
            get {
                return ResourceManager.GetString("imgCopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image was copied to your Clipboard and saved to file!.
        /// </summary>
        public static string imgCopyClipboardSaved {
            get {
                return ResourceManager.GetString("imgCopyClipboardSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Image Width and/or Height is too small!.
        /// </summary>
        public static string imgSize {
            get {
                return ResourceManager.GetString("imgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size exceeds 12 MB! (Try smaller Images or use .JPEG!).
        /// </summary>
        public static string imgTooBig {
            get {
                return ResourceManager.GetString("imgTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Size exceeds 12 MB! (Try smaller/shorter GIFs!).
        /// </summary>
        public static string imgTooBigGif {
            get {
                return ResourceManager.GetString("imgTooBigGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the Imgur Album has been copied to your Clipboard!.
        /// </summary>
        public static string linkAlbumClipboard {
            get {
                return ResourceManager.GetString("linkAlbumClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to Imgur has been copied to your Clipboard!.
        /// </summary>
        public static string linkclipboard {
            get {
                return ResourceManager.GetString("linkclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to Imgur has been copied to your Clipboard and saved to file!.
        /// </summary>
        public static string linkclipboardAndSaved {
            get {
                return ResourceManager.GetString("linkclipboardAndSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging into Imgur Account....
        /// </summary>
        public static string loggingIn {
            get {
                return ResourceManager.GetString("loggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}
        ///
        ///.
        /// </summary>
        public static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File you selected is not a valid Image File!.
        /// </summary>
        public static string notAnImage {
            get {
                return ResourceManager.GetString("notAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured! (Show this to the Smart Computer Apes: {0}).
        /// </summary>
        public static string otherErrorMsg {
            get {
                return ResourceManager.GetString("otherErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Print Key.
        /// </summary>
        public static string printKeyShortcut {
            get {
                return ResourceManager.GetString("printKeyShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image was saved to file!.
        /// </summary>
        public static string savedToFile {
            get {
                return ResourceManager.GetString("savedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to Snipe a new Image.
        /// </summary>
        public static string toSnipeNew {
            get {
                return ResourceManager.GetString("toSnipeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! Sorry about that, it seems like ImgurSniper ran into an unexpected Error!
        ///But no worries, you can help out and get this Problem fixed asap!
        ///Do you want to help out and submit a ticket?
        ///(If you click yes, a new Browser Window opens).
        /// </summary>
        public static string unhandledError {
            get {
                return ResourceManager.GetString("unhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Error occured in ImgurSniper.
        ///Error Message: &quot;{0}&quot;
        ///
        ///Do you want to restart ImgurSniper?.
        /// </summary>
        public static string unhandledErrorDescription {
            get {
                return ResourceManager.GetString("unhandledErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Image... ({0} KB).
        /// </summary>
        public static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading Image to Imgur! ({0}).
        /// </summary>
        public static string uploadingError {
            get {
                return ResourceManager.GetString("uploadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating GIF! ({0}).
        /// </summary>
        public static string uploadingErrorGif {
            get {
                return ResourceManager.GetString("uploadingErrorGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Image... ({0} KB) ({1} of {2}).
        /// </summary>
        public static string uploadingFiles {
            get {
                return ResourceManager.GetString("uploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading GIF... ({0} KB).
        /// </summary>
        public static string uploadingGif {
            get {
                return ResourceManager.GetString("uploadingGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded with ImgurSniper.
        /// </summary>
        public static string uploadTitle {
            get {
                return ResourceManager.GetString("uploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops, something went wrong!.
        /// </summary>
        public static string whoops {
            get {
                return ResourceManager.GetString("whoops", resourceCulture);
            }
        }
    }
}
